### ISSUE TITLE
back to top

### ISSUE THREAD

**Issue by prezine** [CirclepandaLab/pandakit#12]
The "back to top" is a feature for a modern website, and is a layout, so it should be defined within the pandakit.layout.css class and js should be in panda.js file, all class should be strictly JavaScript and in ES6 coding format.
For example:
`// ES5
var x = function(x, y) {
   return x * y;
}

// ES6
const x = (x, y) => x * y;`

**Comment by Chaitanyassr** [comment]
I m working on it.
